### ISSUE TITLE
Autogenerated keys are causing key collision warnings.

### ISSUE THREAD

**Issue by funkybob** [gilbarbara/react-from-dom#1]
In my use case I'm parsing server-supplied HTML-containing labels into React, and rendering them into a list.

```
Warning: Encountered two children with the same key, `0-0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

Ideal solutions would be to either
- allow passing a prefix for all generated keys,
- allow passing a key generator function, or
- allow disabling generating keys for components.

**Comment by gilbarbara** [comment]
Hey @funkybob 
Do you have an example code that generated that?

I think a prefix won't fix that.

**Comment by funkybob** [comment]
In short, I'm iterating a list of records which include an ID and a label. The label may include some HTML, so it must be converted to render properly.

To cite from my addition to the README:
```
function MyComponent({ items: {id: string, label: string}[] }) {
  return (
    <ul>
      {items.map(item => {
        const Node = convert(item.label, {keyPrefix: item.id});
        <li> <Node /> </li>
      })}
    </ul>
  )
}
```

Since the prefix is derived from the record's ID, it yields unique key values for the top level children.

**Comment by funkybob** [comment]
Hmnm... have realised that example likely wouldn't trigger the condition.

It would require rendering the strings inside the same container.

The problem for me originates from my own wrapper for handling a string that doesn't have a single root element... I will delve further and get back to you.

**Comment by funkybob** [comment]
My function is like this:

```
const parser = new DOMParser();

function htmlToReact(input) {
  const doc = parser.parseFromString(input, 'text/html');
  // normalize whitespace and text nodes.
  doc.body.normalize();

  const children = Array.from(doc.body.childNodes).map(convertFromNode);

  if (children.length === 1) {
    return children[0];
  }

  return React.createElement(React.Fragment, null, ...children);
}
```

**Comment by gilbarbara** [comment]
I need to see the input too

**Comment by funkybob** [comment]
So for an example the input :

```
const source = "This is a <strong>simple</strong> example to <em>demonstrate</em> the problem.";
```

This will produce a list like:
```
[
  "This is a ",
  {$$typeof: Symbol(react.element), type: "strong", key: "0-0", ...},
  " example to ",
  {$$typeof: Symbol(react.element), type: "em", key: "0-0", ...},
  " the problem."
]
```

So when passing this to the fragment, it gets two children with the same key value.
[It's clear to me now my PR solution is probably wrong for this...]

Perhaps I should iterate the children and force a prefix on my own...

**Comment by funkybob** [comment]
With a fresh mind and another look at your code, I realised I could fix this by passing in an index value to `convertFromNode`:

```
  const children = Array.from(doc.body.childNodes).map((child, index) => convertFromNode(child, {index}));
```

**Comment by gilbarbara** [comment]
Good to know!

**Comment by funkybob** [comment]
Thanks for being patient with me :)
