### ISSUE TITLE
Doesn't work when multiple actions matches the node

### ISSUE THREAD

**Issue by breezewish** [gilbarbara/react-from-dom#12]
Thanks for the great project! It seems that when multiple actions matches the node the behaviour is strange.

**Comment by gilbarbara** [comment]
hey @breeswish 
Thanks!

I need some code to debug. Please post a codesandbox.

**Comment by gilbarbara** [comment]
If you modify the node in an action, the next iteration might not find the node with the same condition.

**Comment by breezewish** [comment]
Hi @gilbarbara , I see that the current logic is:

```js
  /* istanbul ignore else */
  if (Array.isArray(actions)) {
    actions.forEach((action: Action) => {
      if (action.condition(node, key, level)) {
        if (typeof action.pre === 'function') {
          node = action.pre(node, key, level);

          if (!(node instanceof Node)) {
            node = input;

            /* istanbul ignore else */
            if (process.env.NODE_ENV !== 'production') {
              // eslint-disable-next-line no-console
              console.warn(
                'The `pre` method always must return a valid DomNode (instanceof Node) - your modification will be ignored (Hint: if you want to render a React-component, use the `post` method instead)',
              );
            }
          }
        }

        if (typeof action.post === 'function') {
          result.push(action.post(node, key, level));
        }
      }
    });
  }
```

This means, if there are multiple actions' `condition` matching && `pre` doesn't change anything, there will be multiple elements in the `result` for one `input`.

Is it better to let `post` to accept `ReactNode` instead? This means, multiple `post` can be chained, just like `pre`.

**Comment by gilbarbara** [comment]
Without seeing some code it's impossible to know what is your problem...
