### ISSUE TITLE
Text nodes containing only whitespace are converted to `null`

### ISSUE THREAD

**Issue by GrantGryczan** [gilbarbara/react-from-dom#16]
* Example input: `convert(document.createTextNode('\t \n '))`
Expected output: `'\t \n '`
Actual output: `null`

An example of why this is a problem: `<a>link 1</a> <a>link 2</a>` should have a space between the two links. This removes it.

Another example of why this is a problem: I am using this package to process arbitrary, user-inputted rich text, and the `white-space: pre-wrap` style is applied to the output, which makes whitespace visible.

It is not good to assume it is safe to remove any whitespace. All inputted whitespace should be rendered to the output. If someone, for whatever reason, specifically wants to omit inputted whitespace text nodes from the output, they should use an action, which would be very simple.

**Comment by GrantGryczan** [comment]
If you want, I can try to submit pull requests fixing each of the issues I've submitted so far.

**Comment by GrantGryczan** [comment]
It seems another person ran into this issue in https://github.com/gilbarbara/react-from-dom/issues/7#issuecomment-777103084, but it never got a reply.

**Comment by gilbarbara** [comment]
Fixed in 0.7.0
