### ISSUE TITLE
React's reserved props are not omitted from the inputted DOM and throw errors when rendered to React

### ISSUE THREAD

**Issue by GrantGryczan** [gilbarbara/react-from-dom#18]
## Issue Description

You are able to throw an error in the application by setting React's reserved props as lowercase attributes on inputted DOM elements. Ideally, reserved props should be simply omitted.

React's reserved props can be found here: https://github.com/facebook/react/blob/5890e0e692d1c39eddde0110bd0d123409f31dd3/packages/react-dom/src/shared/DOMProperty.js#L236

## Example Input

```js
const div = document.createElement('div');
div.setAttribute('dangerouslysetinnerhtml', 'any value here');
convert(div);
```

## Expected Output

The reserved prop should be omitted.

```jsx
<div />
```

## Actual Output

`convert` instead outputs this invalid element.

```jsx
<div dangerouslySetInnerHTML="any value here" />
```

React throws an error when trying to render the above element, since `dangerouslySetInnerHTML` does not accept a string. The same applies to most other reserved props.

**Comment by GrantGryczan** [comment]
FYI, I'm not using `react-from-dom` anymore. It is not where I'd like it to be in terms of performance or function, so I'll just write my own DOM-to-React converter which is more optimized and suited for my use case rather than trying to get around yours.

I'm only telling you this so you know I won't be submitting any more pull requests, and to let you know you don't have to fix any of my issues if you don't want to, since I'm probably the only one running into them (at least currently). Though, I don't know how this package is being used elsewhere, so you can be the judge of that.

**Comment by gilbarbara** [comment]
@GrantGryczan Good for you, bye.
