### ISSUE TITLE
Sources are not included in the NPM distribution, which makes the source mapping URLs useless.

### ISSUE THREAD

**Issue by MrJohz** [gilbarbara/react-from-dom#4]
Hi,

I have a step in my webpack build that checks for sourcemaps in include node modules - this helps if I end up debugging an issue that takes me deep into library code for whatever reason.

The `react-from-dom` library has sourcemaps, but the sourcemaps reference sources that aren't included in the final package, which means that the sourcemaps can't be used, as they reference code that I can't use (unless I download the sources from Github and somehow manually link them into the right place!)

My recommendations would be to either:
* Remove sourcemaps entirely from the NPM package - they are currently useless
* Include the sources in the distribution by adding them to the "files" list in NPM
* Include the sources directly in the sourcemaps by using the `inlineSources` TypeScript parameter.

Personally, I think the second option is probably the easiest and the best - the package shouldn't increase significantly in size, and the sources won't be included in downstream bundles anyway.

I can create a pull request for any of these if you want, but they should all be a one-line change anyway.

Thanks for maintaining this library!

**Comment by gilbarbara** [comment]
Hey!

Added the src in 0.4.1

Thanks

**Comment by MrJohz** [comment]
No worries, thanks for adding that!
